enum CommentsActionType {
  GET_ALL_COMMENTS,
  GET_COMMENT,
  CREATE_COMMENT,
  UPDATE_COMMENT,
  UPVOTE_COMMENT,
  DOWNVOTE_COMMENT,
  FLAG_COMMENT,
  DELETE_COMMENT,
  RESET_STATE,
}

export default CommentsActionType;
