enum CommentsActionType {
  GET_ALL_COMMENTS,
  GET_COMMENT,
  CREATE_COMMENT,
  UPDATE_COMMENT,
  UPVOTE_COMMENT,
  DOWNVOTE_COMMENT,
  FLAG_COMMENT,
  DELETE_COMMENT,
  GET_ALL_REPLIES,
  GET_REPLY,
  CREATE_REPLY,
  UPDATE_REPLY,
  UPVOTE_REPLY,
  DOWNVOTE_REPLY,
  FLAG_REPLY,
  DELETE_REPLY,
  RESET_STATE,
}

export default CommentsActionType;
