enum CommentsActionType {
  CREATE_COMMENT,
  UPDATE_COMMENT,
  VOTE_COMMENT,
  FLAG_COMMENT,
  DELETE_COMMENT,
  RESET_STATE,
  CREATE_REPLY,
  UPDATE_REPLY,
  VOTE_REPLY,
  FLAG_REPLY,
  DELETE_REPLY,
}

export default CommentsActionType;
